const PRODUCT_BY_TYPE_REQUEST = "PRODUCT_BY_TYPE_REQUEST";
const PRODUCT_BY_TYPE_SUCCESS = "PRODUCT_BY_TYPE_SUCCESS";
const PRODUCT_BY_TYPE_ERROR = "PRODUCT_BY_TYPE_ERROR";

export {
    PRODUCT_BY_TYPE_REQUEST,
    PRODUCT_BY_TYPE_SUCCESS,
    PRODUCT_BY_TYPE_ERROR
}