const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_ERROR";

export {
    REGISTER_REQUEST,
    REGISTER_SUCCESS,
    REGISTER_ERROR
}