const PRODUCT_TYPE_REQUEST = "PRODUCT_TYPE_REQUEST";
const PRODUCT_TYPE_SUCCESS = "PRODUCT_TYPE_SUCCESS";
const PRODUCT_TYPE_ERROR = "PRODUCT_TYPE_ERROR";

export {
    PRODUCT_TYPE_REQUEST,
    PRODUCT_TYPE_SUCCESS,
    PRODUCT_TYPE_ERROR
}