const ORDER_HISTORY_REQUEST = "ORDER_HISTORY_REQUEST";
const ORDER_HISTORY_SUCCESS = "ORDER_HISTORY_SUCCESS";
const ORDER_HISTORY_ERROR = "ORDER_HISTORY_ERROR";

export {
    ORDER_HISTORY_REQUEST,
    ORDER_HISTORY_SUCCESS,
    ORDER_HISTORY_ERROR
}