const CHAGNE_INFO_REQUEST = "CHAGNE_INFO_REQUEST";
const CHAGNE_INFO_SUCCESS = "CHAGNE_INFO_SUCCESS";
const CHAGNE_INFO_ERROR = "CHAGNE_INFO_ERROR";
const LOGOUT_CHANGE_INFO = "LOGOUT_CHANGE_INFO"

export {
    CHAGNE_INFO_REQUEST,
    CHAGNE_INFO_SUCCESS,
    CHAGNE_INFO_ERROR,
    LOGOUT_CHANGE_INFO
}