const SEND_ORDER_REQUEST = "SEND_ORDER_REQUEST";
const SEND_ORDER_SUCCESS = "SEND_ORDER_SUCCESS";
const SEND_ORDER_ERROR = "SEND_ORDER_ERROR";

export {
    SEND_ORDER_REQUEST,
    SEND_ORDER_SUCCESS,
    SEND_ORDER_ERROR
}